### ISSUE TITLE
Dynamics & ice physics overview issue

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#457]
- [ ] #378 Dynamics switcher
- [ ] #450 Clean up the templates (&c.) in the dynamics code
- [ ] #452 BBMStep should use the BBM solver
- [ ] #453 Free drift dynamics
- [ ] #162 Generating `smesh` files information from restart files
- [ ] #367 Output coordinates in restart files
